#!/usr/bin/env python3
"""Bind a release directory to an existing reviewed Git commit or tree, read-only."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import subprocess
import sys


class SourceMismatch(ValueError):
    pass


# These outputs are regenerated by tools/export.sh before packaging. Never use
# .gitignore as an exemption: it could conceal an extra compiler input.
CLIENT_OUTPUTS = {
    "content.bundle.json", "combat.json", "adventure.json", "progression.json",
    "text.en.json", "campaign.json", "campaign-combat.json", "endgame.json",
    "endgame-combat.json", "phase4-campaign-complete.json", "combat-phase4.json",
    "campaign-combat-phase4.json", "adventure-phase4.json", "progression-phase4.json",
    "campaign-phase4.json", "phase4-migration-manifest.json", "experiments.json",
}
CACHE_DIRECTORIES = {".git", "bin", "obj", ".godot", "__pycache__", "TestResults"}
ROOT_CACHE_DIRECTORIES = {".tools", "artifacts", ".idea", ".vscode"}


def git(repository, *arguments):
    # Ambient index/worktree/replacement/partial-clone configuration must not
    # change the identity being checked or initiate a network fetch.
    env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    env.update(GIT_OPTIONAL_LOCKS="0", GIT_NO_LAZY_FETCH="1",
               GIT_CONFIG_NOSYSTEM="1", GIT_CONFIG_GLOBAL=os.devnull)
    result = subprocess.run(["git", "--no-replace-objects", "-C", str(repository), *arguments],
                            env=env, capture_output=True, check=False)
    if result.returncode:
        raise SourceMismatch("Cannot resolve the source identity in the source repository.")
    return result.stdout


def source_tree(repository, source_id):
    if not re.fullmatch(r"[0-9a-fA-F]{40}|[0-9a-fA-F]{64}", source_id):
        raise SourceMismatch("Source identity must be a full commit or tree hash.")
    source_id = source_id.lower()
    kind = git(repository, "cat-file", "-t", source_id).strip()
    if kind not in (b"commit", b"tree"):
        raise SourceMismatch("Source identity must name a commit or tree object.")
    if git(repository, "rev-parse", "--verify", source_id).decode().strip() != source_id:
        raise SourceMismatch("Source identity must be the full object hash for this repository.")
    tree = git(repository, "rev-parse", "--verify", source_id + "^{tree}").decode().strip()
    entries = {}
    for record in git(repository, "ls-tree", "-rz", "--full-tree", tree).split(b"\0"):
        if not record:
            continue
        metadata, raw_path = record.split(b"\t", 1)
        mode, kind, blob = metadata.decode("ascii").split()
        path = os.fsdecode(raw_path)
        if kind != "blob" or mode not in ("100644", "100755", "120000"):
            raise SourceMismatch("Unsupported source entry (including submodules): " + path)
        if path.startswith("/") or any(part in ("", ".", "..") for part in path.split("/")):
            raise SourceMismatch("Unsafe source path.")
        entries[path] = (mode, blob)
    return tree, entries


def blob_hash(data, object_hash):
    digest = hashlib.new("sha1" if len(object_hash) == 40 else "sha256")
    digest.update(b"blob " + str(len(data)).encode("ascii") + b"\0")
    digest.update(data)
    return digest.hexdigest()


def generated_output(path, entries):
    relative = path.as_posix()
    if path.parent.as_posix() == "game/Ashenwake.Client" and path.name in CLIENT_OUTPUTS:
        return True
    # Godot emits script UID companions during import. Tracked UIDs are checked
    # like all other source files; this exemption only covers generated siblings.
    return relative.endswith((".cs.uid", ".gd.uid")) and relative[:-4] in entries


def verify(directory, repository, source_id):
    directory = Path(directory).resolve(strict=True)
    tree, entries = source_tree(repository, source_id)
    problems = []
    for relative, (mode, expected_hash) in entries.items():
        path = directory / relative
        # Do not follow an unreviewed directory symlink outside this candidate.
        if any(parent.is_symlink() for parent in path.parents if parent != directory and directory in parent.parents):
            problems.append("symlink parent: " + relative)
            continue
        try:
            info = path.lstat()
            if stat.S_ISLNK(info.st_mode):
                actual_mode = "120000"
                data = os.fsencode(os.readlink(path))
            elif stat.S_ISREG(info.st_mode):
                actual_mode = "100755" if info.st_mode & stat.S_IXUSR else "100644"
                data = path.read_bytes()
            else:
                problems.append("not a source file: " + relative)
                continue
            if mode != actual_mode or blob_hash(data, expected_hash) != expected_hash:
                problems.append("changed bytes or mode: " + relative)
        except (FileNotFoundError, NotADirectoryError):
            problems.append("missing: " + relative)

    # Prune caches before descent (including symlinked shared tool caches).
    # Every other undeclared file can affect a wildcard build or exported pack.
    def scan_error(error):
        raise error

    for current, directories, files in os.walk(directory, followlinks=False, onerror=scan_error):
        base = Path(current).relative_to(directory)
        for name in list(directories):
            path = Path(current) / name
            if name in CACHE_DIRECTORIES or (base == Path(".") and name in ROOT_CACHE_DIRECTORIES):
                directories.remove(name)
            elif path.is_symlink():
                directories.remove(name)
                files.append(name)
        for name in files:
            relative = base / name
            path = directory / relative
            if relative.as_posix() in entries or name == ".DS_Store" or relative == Path(".git"):
                continue
            if not path.is_symlink() and path.is_file() and generated_output(relative, entries):
                continue
            problems.append("undeclared file: " + relative.as_posix())
    if problems:
        raise SourceMismatch("Release source differs from the reviewed tree:\n" + "\n".join(sorted(problems)))
    return {"kind": "ReleaseSourceVerified", "sourceId": source_id.lower(),
            "treeId": tree, "trackedFiles": len(entries)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source_id", help="full reviewed Git commit or tree hash")
    parser.add_argument("--source-directory", type=Path, default=Path.cwd())
    args = parser.parse_args()
    repository = Path(os.environ.get("ASHENWAKE_SOURCE_REPOSITORY", str(args.source_directory)))
    try:
        print(json.dumps(verify(args.source_directory, repository, args.source_id), sort_keys=True))
        return 0
    except (SourceMismatch, OSError) as error:
        print(str(error), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
